export const GET_MATCHES = "app/App/GET_MATCHES";
export const GET_MATCHES_SUCCESS = "app/App/GET_MATCHES_SUCCESS";
export const CALCULATE_PLAYER_RATINGS = "app/App/CALCULATE_PLAYER_RATINGS";
export const CALCULATE_PLAYER_RATINGS_SUCCESS =
  "app/App/CALCULATE_PLAYER_RATINGS_SUCCESS";
export const CREATE_RATING_TABLE_DATA = "app/App/CREATE_RATING_TABLE_DATA";
