export const tableRowData = [
  {
    createdAt: "Mar 22, 2020 1:23 AM",
    place: 2,
    standings: "Dry bones, Bowser, Black shy guy, Luigi",
    rating: 1016,
    points: 16,
  },
  {
    createdAt: "Mar 25, 2020 1:23 AM",
    place: 2,
    standings: "Villager, Bowser, Black shy guy, Baby peach",
    rating: 1027,
    points: 11,
  },
  {
    createdAt: "Mar 26, 2020 1:23 AM",
    place: 3,
    standings: "Waluigi, Luigi, Bowser, Black shy guy",
    rating: 1003,
    points: -24,
  },
  {
    createdAt: "Mar 27, 2020 1:23 AM",
    place: 4,
    standings: "Dry bones, Mario, Waluigi, Bowser",
    rating: 960,
    points: -43,
  },
  {
    createdAt: "Apr 5, 2020 1:23 AM",
    place: 4,
    standings: "Waluigi, Villager, Baby peach, Bowser",
    rating: 924,
    points: -36,
  },
  {
    createdAt: "Apr 9, 2020 1:23 AM",
    place: 4,
    standings: "Waluigi, Dry bones, Mario, Bowser",
    rating: 890,
    points: -34,
  },
  {
    createdAt: "Apr 11, 2020 1:23 AM",
    place: 2,
    standings: "Luigi, Bowser, Baby peach, Black shy guy",
    rating: 913,
    points: 23,
  },
  {
    createdAt: "Apr 12, 2020 1:23 AM",
    place: 4,
    standings: "Luigi, Baby peach, Mario, Bowser",
    rating: 874,
    points: -39,
  },
  {
    createdAt: "Apr 13, 2020 1:23 AM",
    place: 3,
    standings: "Baby peach, Black shy guy, Bowser, Dry bones",
    rating: 864,
    points: -10,
  },
  {
    createdAt: "Apr 14, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Mario, Luigi, Baby peach",
    rating: 932,
    points: 68,
  },
  {
    createdAt: "Apr 16, 2020 1:23 AM",
    place: 4,
    standings: "Waluigi, Dry bones, Black shy guy, Bowser",
    rating: 887,
    points: -45,
  },
  {
    createdAt: "Apr 17, 2020 1:23 AM",
    place: 3,
    standings: "Dry bones, Mario, Bowser, Villager",
    rating: 889,
    points: 2,
  },
  {
    createdAt: "Apr 19, 2020 1:23 AM",
    place: 4,
    standings: "Mario, Dry bones, Black shy guy, Bowser",
    rating: 853,
    points: -36,
  },
  {
    createdAt: "Apr 23, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Mario, Dry bones, Luigi",
    rating: 925,
    points: 72,
  },
  {
    createdAt: "Apr 24, 2020 1:23 AM",
    place: 2,
    standings: "Luigi, Bowser, Dry bones, Baby peach",
    rating: 950,
    points: 25,
  },
  {
    createdAt: "Apr 27, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Villager, Black shy guy, Mario",
    rating: 1005,
    points: 55,
  },
  {
    createdAt: "Apr 28, 2020 1:23 AM",
    place: 2,
    standings: "Mario, Bowser, Luigi, Villager",
    rating: 1023,
    points: 18,
  },
  {
    createdAt: "Apr 29, 2020 1:23 AM",
    place: 3,
    standings: "Waluigi, Mario, Bowser, Villager",
    rating: 1010,
    points: -13,
  },
  {
    createdAt: "May 1, 2020 1:23 AM",
    place: 4,
    standings: "Waluigi, Mario, Dry bones, Bowser",
    rating: 969,
    points: -41,
  },
  {
    createdAt: "May 2, 2020 1:23 AM",
    place: 2,
    standings: "Black shy guy, Bowser, Waluigi, Baby peach",
    rating: 986,
    points: 17,
  },
  {
    createdAt: "May 3, 2020 1:23 AM",
    place: 3,
    standings: "Baby peach, Luigi, Bowser, Black shy guy",
    rating: 968,
    points: -18,
  },
  {
    createdAt: "May 4, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Mario, Luigi, Waluigi",
    rating: 1032,
    points: 64,
  },
  {
    createdAt: "May 9, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Luigi, Black shy guy, Mario",
    rating: 1075,
    points: 43,
  },
  {
    createdAt: "May 12, 2020 1:23 AM",
    place: 4,
    standings: "Baby peach, Dry bones, Mario, Bowser",
    rating: 1013,
    points: -62,
  },
  {
    createdAt: "May 15, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Black shy guy, Dry bones, Mario",
    rating: 1055,
    points: 42,
  },
  {
    createdAt: "May 16, 2020 1:23 AM",
    place: 2,
    standings: "Waluigi, Bowser, Black shy guy, Villager",
    rating: 1065,
    points: 10,
  },
  {
    createdAt: "May 17, 2020 1:23 AM",
    place: 3,
    standings: "Baby peach, Mario, Bowser, Luigi",
    rating: 1039,
    points: -26,
  },
  {
    createdAt: "May 19, 2020 1:23 AM",
    place: 2,
    standings: "Baby peach, Bowser, Villager, Black shy guy",
    rating: 1053,
    points: 14,
  },
  {
    createdAt: "May 20, 2020 1:23 AM",
    place: 2,
    standings: "Waluigi, Bowser, Black shy guy, Villager",
    rating: 1060,
    points: 7,
  },
  {
    createdAt: "May 21, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Villager, Luigi, Dry bones",
    rating: 1094,
    points: 34,
  },
  {
    createdAt: "May 22, 2020 1:23 AM",
    place: 3,
    standings: "Luigi, Baby peach, Bowser, Mario",
    rating: 1067,
    points: -27,
  },
  {
    createdAt: "May 25, 2020 1:23 AM",
    place: 3,
    standings: "Baby peach, Villager, Bowser, Luigi",
    rating: 1046,
    points: -21,
  },
  {
    createdAt: "May 26, 2020 1:23 AM",
    place: 4,
    standings: "Dry bones, Baby peach, Villager, Bowser",
    rating: 994,
    points: -52,
  },
  {
    createdAt: "May 27, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Mario, Villager, Luigi",
    rating: 1036,
    points: 42,
  },
  {
    createdAt: "May 29, 2020 1:23 AM",
    place: 3,
    standings: "Black shy guy, Mario, Bowser, Dry bones",
    rating: 1013,
    points: -23,
  },
  {
    createdAt: "Jun 1, 2020 1:23 AM",
    place: 2,
    standings: "Baby peach, Bowser, Luigi, Black shy guy",
    rating: 1032,
    points: 19,
  },
  {
    createdAt: "Jun 3, 2020 1:23 AM",
    place: 2,
    standings: "Villager, Bowser, Luigi, Dry bones",
    rating: 1038,
    points: 6,
  },
  {
    createdAt: "Jun 7, 2020 1:23 AM",
    place: 2,
    standings: "Baby peach, Bowser, Villager, Mario",
    rating: 1048,
    points: 10,
  },
  {
    createdAt: "Jun 8, 2020 1:23 AM",
    place: 2,
    standings: "Waluigi, Bowser, Baby peach, Black shy guy",
    rating: 1062,
    points: 14,
  },
  {
    createdAt: "Jun 9, 2020 1:23 AM",
    place: 3,
    standings: "Black shy guy, Dry bones, Bowser, Mario",
    rating: 1033,
    points: -29,
  },
  {
    createdAt: "Jun 10, 2020 1:23 AM",
    place: 4,
    standings: "Dry bones, Luigi, Baby peach, Bowser",
    rating: 979,
    points: -54,
  },
  {
    createdAt: "Jun 11, 2020 1:23 AM",
    place: 4,
    standings: "Baby peach, Black shy guy, Dry bones, Bowser",
    rating: 938,
    points: -41,
  },
  {
    createdAt: "Jun 13, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Villager, Luigi, Black shy guy",
    rating: 995,
    points: 57,
  },
  {
    createdAt: "Jun 17, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Mario, Dry bones, Black shy guy",
    rating: 1041,
    points: 46,
  },
  {
    createdAt: "Jun 19, 2020 1:23 AM",
    place: 2,
    standings: "Black shy guy, Bowser, Mario, Dry bones",
    rating: 1045,
    points: 4,
  },
  {
    createdAt: "Jun 20, 2020 1:23 AM",
    place: 3,
    standings: "Luigi, Black shy guy, Bowser, Baby peach",
    rating: 1026,
    points: -19,
  },
  {
    createdAt: "Jun 21, 2020 1:23 AM",
    place: 2,
    standings: "Black shy guy, Bowser, Luigi, Baby peach",
    rating: 1042,
    points: 16,
  },
  {
    createdAt: "Jun 23, 2020 1:23 AM",
    place: 3,
    standings: "Dry bones, Mario, Bowser, Baby peach",
    rating: 1019,
    points: -23,
  },
  {
    createdAt: "Jun 24, 2020 1:23 AM",
    place: 3,
    standings: "Baby peach, Dry bones, Bowser, Waluigi",
    rating: 1003,
    points: -16,
  },
  {
    createdAt: "Jun 25, 2020 1:23 AM",
    place: 1,
    standings: "Bowser, Luigi, Mario, Black shy guy",
    rating: 1050,
    points: 47,
  },
  {
    createdAt: "Jun 27, 2020 1:23 AM",
    place: 4,
    standings: "Waluigi, Mario, Dry bones, Bowser",
    rating: 998,
    points: -52,
  },
  {
    createdAt: "Jun 28, 2020 1:23 AM",
    place: 4,
    standings: "Luigi, Waluigi, Villager, Bowser",
    rating: 950,
    points: -48,
  },
  {
    createdAt: "Jun 28, 2020 4:08 PM",
    place: 4,
    standings: "Mario, Luigi, Baby peach, Bowser",
    rating: 913,
    points: -37,
  },
  {
    createdAt: "Jun 28, 2020 4:11 PM",
    place: 3,
    standings: "Mario, Villager, Bowser, Black shy guy",
    rating: 904,
    points: -9,
  },
  {
    createdAt: "Jun 28, 2020 4:12 PM",
    place: 2,
    standings: "Mario, Bowser, Villager, Luigi",
    rating: 936,
    points: 32,
  },
  {
    createdAt: "Jun 28, 2020 4:19 PM",
    place: 1,
    standings: "Bowser, Black shy guy, Dry bones, Baby peach",
    rating: 989,
    points: 53,
  },
  {
    createdAt: "Jun 28, 2020 4:20 PM",
    place: 3,
    standings: "Villager, Luigi, Bowser, Black shy guy",
    rating: 967,
    points: -22,
  },
  {
    createdAt: "Jun 28, 2020 4:27 PM",
    place: 4,
    standings: "Baby peach, Dry bones, Mario, Bowser",
    rating: 929,
    points: -38,
  },
  {
    createdAt: "Jun 29, 2020 3:15 PM",
    place: 3,
    standings: "Luigi, Waluigi, Bowser, Black shy guy",
    rating: 923,
    points: -6,
  },
  {
    createdAt: "Jun 29, 2020 3:46 PM",
    place: 1,
    standings: "Bowser, Villager, Mario, Black shy guy",
    rating: 977,
    points: 54,
  },
  {
    createdAt: "Jun 29, 2020 5:44 PM",
    place: 1,
    standings: "Bowser, Baby peach, Black shy guy, Villager",
    rating: 1026,
    points: 49,
  },
  {
    createdAt: "Jun 30, 2020 3:30 AM",
    place: 3,
    standings: "Baby peach, Dry bones, Bowser, Waluigi",
    rating: 1012,
    points: -14,
  },
];

export const tableColumns = [
  {
    field: "createdAt",
    title: "Match Date / Time",
    type: "datetime",
    customSort: (a, b) => {
      const timeA = moment(new Date(a.createdAt)).valueOf();
      const timeB = moment(new Date(b.createdAt)).valueOf();
      return timeA < timeB ? -1 : timeA > timeB ? 1 : 0;
    },
  },
  { field: "place", title: "Place", type: "numeric" },
  {
    field: "standings",
    title: "Standings",
    sorting: false,
  },
  {
    field: "rating",
    title: "Rating At Match End",
    type: "numeric",
  },
  {
    field: "points",
    title: "Points Won / Lost",
    type: "numeric",
    cellStyle: { textAlign: "center" },
    headerStyle: { textAlign: "right" },
  },
];
